### PR TITLE
Add resume

### PR DESCRIPTION
**Pull request by ianbarker**
Add support for resuming file uploads

### CODE REVIEW

**Comment by rico345100** [comment]
Thank you for pull request and sorry for late answer. However, changes almost about indents, it is hard to find what is the difference between your code and old one.

Also resuming file upload doesn't needed necessary I think, this module have to focus on "uploading" it self, and resuming could be resolved by programming, but may we need more discussion about it.

**Comment by ianbarker** [comment]
Sorry, I think my IDE must have changed the indents. I'll sort that and re-commit at some point. I needed the resume facility so I thought I might as well submit it for others. How would you suggest resuming without altering the module? That might be a better solution for my use case as well.

**Comment by rico345100** [comment]
I've been thinking about this for days, and I think resuming quite handy if someone needed like you.

My motto of making program was "Do as simple as possible, Gives minimum functionalities, so that each module do they're work clearly".

From that point of view, adding "resuming" into this module seems unsuitable.

By the way socket.io-file module is abstracted higher level module of socket.io that provides file uploading feature with extra functionalities like renaming, multiple path uploading and others, some of them were requested other users wanted to.

So adding resuming could be fine and thus might be helpful someone needed like you.

Please let me know after you re-commit your code.

**Comment by ianbarker** [comment]
Hi I've finally managed to get around to changing the indents back to tabs so hopefully you can review these changes more easily now. Sorry it took so long.

**Comment by ianbarker** [comment]
I'll create a new PR for this with indent stuff fixed/removed

**Pull request closed without merging**
